import { Concept, Person } from './encyclopedia';

export const generatedConcepts: Concept[] = [
  {
    slug: "tevhid",
    title: "Tevhid",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Tevhid hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "adalet",
    title: "Adalet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Adalet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "nubuvvet",
    title: "Nübüvvet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Nübüvvet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-mamet",
    title: "İmamet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İmamet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mead",
    title: "Mead",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Mead hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "velayet",
    title: "Velayet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Velayet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "velayet-i-tekvini",
    title: "Velayet-i Tekvini",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Velayet-i Tekvini hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "velayet-i-tesrii",
    title: "Velayet-i Teşrii",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Velayet-i Teşrii hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-smet",
    title: "İsmet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İsmet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sefaat",
    title: "Şefaat",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Şefaat hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "tevessul",
    title: "Tevessül",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Tevessül hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "takiyye",
    title: "Takiyye",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Takiyye hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "beda",
    title: "Beda",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Beda hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "recat",
    title: "Recat",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Recat hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "gaybet",
    title: "Gaybet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Gaybet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-ntizar",
    title: "İntizar",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İntizar hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "zuhur",
    title: "Zuhur",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Zuhur hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mehdeviyet",
    title: "Mehdeviyet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Mehdeviyet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "gaybet-i-sugra",
    title: "Gaybet-i Suğra",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Gaybet-i Suğra hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "gaybet-i-kubra",
    title: "Gaybet-i Kübra",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Gaybet-i Kübra hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "niyabet-i-hassa",
    title: "Niyabet-i Hassa",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Niyabet-i Hassa hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "niyabet-i-amme",
    title: "Niyabet-i Amme",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Niyabet-i Amme hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sefirler",
    title: "Sefirler",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Sefirler hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sufyani",
    title: "Süfyani",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Süfyani hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "yemani",
    title: "Yemani",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Yemani hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "deccal",
    title: "Deccal",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Deccal hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "313",
    title: "313",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "313 hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "gadir",
    title: "Gadir",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Gadir hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sekaleyn",
    title: "Sekaleyn",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Sekaleyn hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mubahele",
    title: "Mübahele",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Mübahele hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "fadak",
    title: "Fadak",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Fadak hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ehl-i-beyt",
    title: "Ehl-i Beyt",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Ehl-i Beyt hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "l-i-aba",
    title: "Âl-i Aba",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Âl-i Aba hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "hadis-i-kisa",
    title: "Hadis-i Kisa",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Hadis-i Kisa hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "kerbel",
    title: "Kerbelâ",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Kerbelâ hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "asura",
    title: "Aşura",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Aşura hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "erbain",
    title: "Erbain",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Erbain hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ziyaret",
    title: "Ziyaret",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Ziyaret hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ziyaret-i-asura",
    title: "Ziyaret-i Aşura",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Ziyaret-i Aşura hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sehadet",
    title: "Şehadet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Şehadet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mersiye",
    title: "Mersiye",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Mersiye hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "azadarlik",
    title: "Azadarlık",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Azadarlık hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "nehcu-l-bel-ga",
    title: "Nehcü'l-Belâğa",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Nehcü'l-Belâğa hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sahife-i-seccadiye",
    title: "Sahife-i Seccadiye",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Sahife-i Seccadiye hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "kutub-i-erbaa",
    title: "Kütüb-i Erbaa",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Kütüb-i Erbaa hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "el-kafi",
    title: "el-Kafi",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "el-Kafi hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "men-la-yahduruhu-l-fakih",
    title: "Men La Yahduruhu'l-Fakih",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Men La Yahduruhu'l-Fakih hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "tehzibu-l-ahkam",
    title: "Tehzibü'l-Ahkam",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Tehzibü'l-Ahkam hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "el-i-stibsar",
    title: "el-İstibsar",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "el-İstibsar hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "usul-i-din",
    title: "Usul-i Din",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Usul-i Din hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "furu-i-din",
    title: "Füru-i Din",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Füru-i Din hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "marifetullah",
    title: "Marifetullah",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Marifetullah hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "huccet",
    title: "Huccet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Huccet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "vasi",
    title: "Vasi",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Vasi hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-mam",
    title: "İmam",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İmam hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "masum",
    title: "Masum",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Masum hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "takva",
    title: "Takva",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Takva hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sabir",
    title: "Sabır",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Sabır hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "zuhd",
    title: "Zühd",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Zühd hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-hlas",
    title: "İhlas",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İhlas hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "dua",
    title: "Dua",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Dua hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "munacat",
    title: "Münacat",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Münacat hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "tovbe",
    title: "Tövbe",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Tövbe hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "marifet",
    title: "Marifet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Marifet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-rfan",
    title: "İrfan",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "İrfan hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "akl",
    title: "Akl",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Akl hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "nefs",
    title: "Nefs",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Nefs hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "kalp",
    title: "Kalp",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Kalp hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "adalet",
    title: "Adalet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Adalet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mazlumiyet",
    title: "Mazlumiyet",
    arabicTitle: "TBA",
    shortDefinition: "Yapay zeka tarafından oluşturulmuş taslak içerik.",
    definition: "Mazlumiyet hakkında yapay zeka tarafından üretilmiş detaylı taslak açıklama. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    etymology: "TBA",
    quranicUsage: "TBA",
    hadithUsage: "TBA",
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bibliography: [],
    aiGenerated: true,
    editorialStatus: 'draft'
  }
];

export const generatedScholars: Person[] = [
  {
    slug: "seyh-kuleyni",
    name: "Şeyh Kuleyni",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Kuleyni hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyh-saduk",
    name: "Şeyh Saduk",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Saduk hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyh-mufid",
    name: "Şeyh Müfid",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Müfid hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyh-tusi",
    name: "Şeyh Tusi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Tusi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "serif-murtaza",
    name: "Şerif Murtaza",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şerif Murtaza hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "serif-radi",
    name: "Şerif Radi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şerif Radi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "allame-hilli",
    name: "Allame Hilli",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Allame Hilli hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "muhakkik-hilli",
    name: "Muhakkik Hilli",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Muhakkik Hilli hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "allame-meclisi",
    name: "Allame Meclisi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Allame Meclisi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyh-hurr-amili",
    name: "Şeyh Hurr Amili",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Hurr Amili hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "allame-tabatabai",
    name: "Allame Tabatabai",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Allame Tabatabai hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ayetullah-hoyi",
    name: "Ayetullah Hoyi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Ayetullah Hoyi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "i-mam-humeyni",
    name: "İmam Humeyni",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "İmam Humeyni hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sehid-mutahhari",
    name: "Şehid Mutahhari",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şehid Mutahhari hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sehid-sadr",
    name: "Şehid Sadr",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şehid Sadr hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "feyz-kasani",
    name: "Feyz Kaşani",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Feyz Kaşani hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "mir-damad",
    name: "Mir Damad",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Mir Damad hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "molla-sadra",
    name: "Molla Sadra",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Molla Sadra hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyyid-i-bn-tavus",
    name: "Seyyid İbn Tavus",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Seyyid İbn Tavus hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sehid-i-evvel",
    name: "Şehid-i Evvel",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şehid-i Evvel hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "sehid-i-sani",
    name: "Şehid-i Sani",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şehid-i Sani hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyh-bahai",
    name: "Şeyh Bahai",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Şeyh Bahai hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "seyyid-ebu-l-kasim-el-hoyi",
    name: "Seyyid Ebu'l Kasım el-Hoyi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Seyyid Ebu'l Kasım el-Hoyi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ayetullah-sistani",
    name: "Ayetullah Sistani",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Ayetullah Sistani hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  },
  {
    slug: "ayetullah-burucerdi",
    name: "Ayetullah Burucerdi",
    title: "Şiî Âlim",
    laqabs: [],
    kunyas: [],
    birth: "TBA",
    birthPlace: "TBA",
    death: "TBA",
    father: "TBA",
    mother: "TBA",
    teachers: [],
    students: [],
    relatedBooks: [],
    relatedArticles: [],
    relatedPersons: [],
    bio: "Ayetullah Burucerdi hakkında yapay zeka tarafından üretilmiş taslak biyografi. Bu içerik editoryal incelemeden geçmeden yayına alınmamalıdır. [VERIFY SOURCE]",
    aiGenerated: true,
    editorialStatus: 'draft'
  }
];
